### ISSUE TITLE
Increase summary line length?

### ISSUE THREAD

**Issue by dideler** [tpope/vim-git#21]
The summary line length is currently at 50. The best reason I could find for that was your blog post about [commit messages](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).

>  The subject line is used all over Git, oftentimes in truncated form if too long of a message was used

From what I've found, up to 58 characters works just as well -- it's not being truncated on GitHub or in Git, though I haven't tried an exhaustive list of commands. I haven't tried any more than 58, but will update when I do.

IIRC, summary lines above ~50 chars would previously show up as truncated on GitHub, but they must have increased the limit. It now seems to be [truncated at 70 chars](https://github.com/rton/freeseer/commit/310e9ba3c6d3d4d3251ff6e3ae7cc6708efdaa30) (so 69 is max).

**Comment by ELLIOTTCABLE** [comment]
Per [Ingo's response on S.O.](http://superuser.com/a/887744/22030), I'm popping in here to ask that this be somehow configurable, instead of having to be overridden at the syntax level.

:+1:
