### ISSUE TITLE
Can I safely remove commit spell check and line wrapping in my vimrc?

### ISSUE THREAD

**Issue by dideler** [tpope/vim-git#22]
In my .vimrc I have

``` vimscript
" Add spell checking and automatic wrapping at the recommended 72 columns to commit messages.
autocmd Filetype gitcommit setlocal spell textwidth=72
```

Does vim-git already take care of this?

**Comment by lencioni** [comment]
> You're on your own for spellcheck though; can't really get away with setting that in an ftplugin.

Can you explain what you mean by not being able to get away with setting this in an ftplugin?
