### ISSUE TITLE
Wrapping asterisk bullet lists in gitcommit

### ISSUE THREAD

**Issue by ienorand** [tpope/vim-git#41]
Currently, when wrapping lines starting with an asterisk in the commit message it gets wrapped as though it was a C comment:

```
* text text text text text text text text text text text text text text text text text text text text text text text
```

```
* text text text text text text text text text text text text text text 
* text text text text text text text text text
```

Would it be possible to add something like

```
setlocal comments-=mb:*
setlocal comments+=fb:*
```

to the gitcommit format specifier in order to allow reasonable wrap-handling of asterisk-bullted lists in commit messages, or would this interfere with the diff format of git commit --verbose?

**Comment by wjrogers** [comment]
I swear this used to work, but today I can't get vim to wrap my bullet lists with a hanging indent at all. Is gitcommit filemode supposed to support hanging indents? If so, what's the right combination of spaces and bullet characters?

**Comment by ienorand** [comment]
It works fine with dashes as bullet character, but asterisks are treated as though they were c-comment characters instead.

**Comment by tpope** [comment]
Wait, what? [We already adjust that option](https://github.com/tpope/vim-git/blob/a08ca046128988beb3461d44de91524350be7678/ftplugin/gitcommit.vim#L14).

**Comment by ienorand** [comment]
Indeed, I'm apparently using an older version (The one shipped with 2:7.4.488-7+deb8u2 in Debian).

Based on the date in the file header being equivalent (2013), I assumed it was the same.

As far as I can tell though, by adding that option in vim-git, this overwrites all wrapping settings, as noted in https://github.com/lencioni/dotfiles/commit/a3aefb5c10a80de49309c1b1970fa8d2b53e8a33

Is that really intended?

**Comment by jsatk** [comment]
I'm in the same boat. I can't get hanging indent to work out of the box. I have nothing in my person `~/.vimrc` related to git. This is really the only plugin I have related to git stuffs.

**Comment by tpope** [comment]
This appears to work out of the box so long as `'autoindent'` is set. This option is off by default with an empty vimrc but is enabled by `defaults.vim`.
