### ISSUE TITLE
Incorrect syntax highlighting in gitconfig for git alias `!git a; git b`

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-git#42]
Consider following alias in `~/.config/git/config`
```
[alias]
  config-user-ME = !git config user.name "ME"; git config user.email "me@github.com"
```
In `$VIMRUNTIME/ftplugin/gitconfig.vim comments are correctly setup,
```viml
setlocal comments=:#,:; commentstring=;\ %s
```
However, the syntax highlighting gets messed up for such aliases.

I guess there is no perfect solution. I use the workaround using `&&` instead of `;` which is semantically not identically but who cares here

**Comment by adriaanzon** [comment]
It could be solved by including `syntax/sh.vim` with `:syn include`, for everything that comes after the `!` in `gitconfigAssignment`.

That would highlight other shell things like `"$(basename "$(git rev-parse --show-toplevel)")"` correctly too.

**Comment by tpope** [comment]
In my gitconfig:

```
[alias]
	test = !echo 1; echo 2
```

When I run it:
```
$ git test
1
$
```

The highlighting is right. Your alias is wrong.

**Comment by adriaanzon** [comment]
@kiryph do you see a `2` when you run `git test` with that alias?

**Comment by kiryph** [comment]
@adriaanzon No, I don't see a `2`. I see, my original alias is indeed wrong. Thanks for pointing this out.

I guess following alias is correct (and no syntax highlighting issue):

```
    test = "!sh -c 'echo 1; echo 2'"
```

```
$ git test
1
2
```

**Comment by kiryph** [comment]
I've just noticed another working version of this alias

```
    test = !echo 1";" echo 2
```

I prefer this one because there is no second shell invocation.

Details about valid syntax can be found here https://git-scm.com/docs/git-config#_syntax.
