### ISSUE TITLE
Red/green diff highlighting in gitcommit message goes away after saving buffer

### ISSUE THREAD

**Issue by danielyli** [tpope/vim-git#43]
After editing a commit message and saving but not exiting the buffer (`:w` instead of `:x`), the red and green diff below the message stops being colored.

**Comment by tpope** [comment]
There's a lot that could be going wrong, but my first suggestion would be to try a different color scheme. The fact you have actual red and green suggests it's doing something special for diffs.

**Comment by danielyli** [comment]
Gotcha.  I'll check it out and append to this issue if it's not a color scheme problem.

**Comment by oluckyman** [comment]
I have a similar issue.
Without any edits, just when I do `:Gstatus` it looks like this (no green and red):
![image](https://user-images.githubusercontent.com/642673/27096682-22390fbc-5072-11e7-8643-e513b6cfa7f5.png)

**Comment by oluckyman** [comment]
Checked on solarized theme: works fine. Seems it’s the problem in [seoul256](https://github.com/junegunn/seoul256.vim) theme which I’m using.

**Comment by tpope** [comment]
Your screenshot is the intended effect. Solarized insists on completely jacking it up for whatever reason.

**Comment by wonka1** [comment]
i need some advice on which permisions to grant 
to the git.hub site,i didnt intened  to revoke all 
permisions perminatly.i was testing my level of 
status on the site and quickly realized,I do,have root source rights to add or remove any permisions,repositories,depositories,trusted cert,
as well as grant,share,revoke or dissmiss any app or site if  feel they are acting un-ethicly,illegaly,
violateing my privacy rights when in private or public domains.intellectual property or trademarks of me,or my partners.also there will be data limits set for public use,and analytics 
to maintain a fair structure of data distribution 
for all useing the platform."NO data hogs,like facebook.useing agressive algorythems."

**Comment by tpope** [comment]
Assuming this is a color scheme issue. We're not doing anything unusual with respect to diff highlighting.
