### ISSUE TITLE
[Feature Request] Highlight gitcommitFirstLine characters past 72

### ISSUE THREAD

**Issue by AndrewSB** [tpope/vim-git#49]
Hey Tim, 
I was wondering what your opinion on highlighting characters past 72 on the `gitcommitFirstLine` was. I sometimes use Atom's commit editor, and I think they do a great job at this ⬇️

![Atom highlighting](https://user-images.githubusercontent.com/25517624/27290837-6ec82264-54dc-11e7-845d-c770b64493f2.png)

Albiet 80 characters, not 72.

I'm aware that the commit line will wrap the next word after 72 characters in the `gitcommitFirstLine`, but I think the highlighting would make my brevity more obvious, faster. If you think this is a good idea, I'd be more than happy to volunteer my time to implement the behavior and send a Pull Request.

Thank you so much for all of your work ❤️

**Comment by tpope** [comment]
Not super keen on the idea at first glance. The existing 50 character highlighting feels a bit too aggressive to me these days.

But let's start with your "more obvious, faster" argument. Doesn't Vim *immediately* wrap when you hit 72 characters? With the default settings, I think the only time this highlighting would even be visible would be for a single 73 character word.

**Comment by AndrewSB** [comment]
That's kind of how I feel, but I see the 50 character highlighting more as a gentle reminder to be succinct, and the

**Comment by AndrewSB** [comment]
My mistake! It does immediately wrapped, for some reason I was deluded into thinking it only broke after I added a new space. That deems my FR unnecessary.

I see the 50 character highlighting more as a gentle reminder to be succinct, and then the break as an aggressive reminder that I might be doing something wrong.
