### ISSUE TITLE
Hanging indents for bulleted lists do not work

### ISSUE THREAD

**Issue by jsatk** [tpope/vim-git#56]
When I use bulleted lists with `-` or `*` lines that are longer than 72 chars do not wrap with a hanging ident.

What I'd expect:

```gitcommit
- This is a long line that wraps
  and aligns the second line and
  even the third line.
```

What I get:

```gitcommit
- This is a long line that wraps
and unfortunately it indents all 
the way over to the left.
```

I dug into this locally for quite awhile but couldn't figure out the right combination of settings for `formatoptions` to make this work.

**Comment by codeinthehole** [comment]
Fix here: https://github.com/tpope/vim-git/pull/60

**Comment by jsatk** [comment]
Thank you @codeinthehole.
