### ISSUE TITLE
Git comment char not being respected for comments

### ISSUE THREAD

**Issue by jacobbednarz** [tpope/vim-git#59]
Within my `gitconfig`, I have the my `core.commentChar` set to `|` due to using `#` in majority of my commits for other non-comment related things. Unfortunately, it looks like the [gitcommit syntax](https://github.com/tpope/vim-git/blob/master/syntax/gitcommit.vim#L30) is hardcoded to use `^#.*`.

I had a bit of a poke around and I couldn't find a way that instead of using a hardcoded value, I could rely on the value from `core.commentChar`. Is this something that is possible? If you have some documentation or guides to point me at, I'm happy to submit a PR for this one.

Thanks!

**Comment by tpope** [comment]
Checking `core.commentChar` would mean shelling out to `git config` every time, not a cost I am willing to impose on the 99.9% of people who don't need it. I would tolerate an option, even though it means adding a bunch of hard to read `:execute` statements.

**Comment by jacobbednarz** [comment]
Shelling out for such a small usage would be 💩 I'm not too attached to this issue and happy to close it as it's a minor annoyance for now unless you either have a suitable solution that doesn't uglify things too much or think it would be useful for others.

**Comment by tpope** [comment]
It would be pretty ugly, which as I said I will tolerate but am certainly not in a hurry to implement myself.
