### ISSUE TITLE
Green syntax highlighting is used where it should be red

### ISSUE THREAD

**Issue by dylan-chong** [tpope/vim-git#62]
[git-repo.zip](https://github.com/tpope/vim-git/files/2990067/assignment1.zip)

inside the attached Git repository I type `git show` and scroll down a little bit I see this (correct diff):

<img width="526" alt="Screenshot 2019-03-21 at 9 46 43 AM" src="https://user-images.githubusercontent.com/17482349/54718155-c73c5480-4bbe-11e9-8743-a269f9f44046.png">

However when I type `git commit --amend` which opens Vim, and school down a bit I see this incorrect syntax highlighting on the `TODO`  line - It is green instead of red:

<img width="434" alt="Screenshot 2019-03-21 at 9 46 52 AM" src="https://user-images.githubusercontent.com/17482349/54718158-c86d8180-4bbe-11e9-8d7c-145f4fda2227.png">

I am using the latest Vim polyglot

**Comment by tpope** [comment]
This is Vim's default for highlighting the `diff` file type. I hate it too, but I don't think it's my place to fight it. Many third party color schemes provide better defaults.
