### ISSUE TITLE
Still need install vim-git in vim-8.0?

### ISSUE THREAD

**Issue by qc1iu** [tpope/vim-git#65]
I found that vim-git has been in vim-8.0  by default, I'm not sure whether vim-git has been integrated in previous version, and is that means we don't need to install vim-git as a plugin. Or it has some difference with the default version?

**Comment by tpope** [comment]
It's been there since Vim 7.2. Nobody needs to install this unless you're intending to test the development version/send a patch.

**Comment by qc1iu** [comment]
Thks, @tpope .
