### ISSUE TITLE
How to highlight trailing full stop in first line of gitcommit?

### ISSUE THREAD

**Issue by airblade** [tpope/vim-git#66]
I have a habit, which I would like to break, of ending the first line of my commits with a full stop.  To do this I want to highlight the full stop but I can't figure out how.

After looking at [these lines](https://github.com/tpope/vim-git/blob/ca2645abf96f6f6daaef55dbfaf64f7f77713150/syntax/gitcommit.vim#L21-L31) I tried this but it didn't work:

```viml
au Filetype gitcommit syn match ErrorMsg "\.$" containedin=gitcommitFirstLine
```

It also didn't work without the `containedin`.

Any pointers would be much appreciated.  Many thanks in advance.

**Comment by tpope** [comment]
You want a `Syntax` event, not a `FileType` event. And if that doesn't work try an `after/` file.

**Comment by airblade** [comment]
Thank you, that helped.

It turned out I also had to tell `gitcommitSummary` it could contain my match group.

```viml
" after/syntax/gitcommit.vim
syn match gitcommitTrailingFullStop "\.$" contained
syn match gitcommitSummary  "^.*\%<51v." contained containedin=gitcommitFirstLine nextgroup=gitcommitOverflow contains=@Spell,gitcommitTrailingFullStop
hi def link gitcommitTrailingFullStop Error
```

Now it all works as I wanted.

**Comment by halostatue** [comment]
This is the version required with Vim 9:

```vim
scriptencoding utf-8

" Highlight trailing full stop in commit summary as an error.

syn match gitcommitTrailingFullStop "\.$" contained containedin=gitcommitSummary

" Override existing syntax match so it can contain my match.
" https://github.com/tpope/vim-git/blob/master/syntax/gitcommit.vim#L24-L28

let s:summary_length = get(g:, 'gitcommit_summary_length', 50)
let s:pattern = s:summary_length < 0 ? '^.*$' : printf('^.*\%%<%dv.', s:summary_length + 1)

execute printf(
  'syn match gitcommitSummary "%s" contained containedin=%s nextgroup=%s contains=%s',
  s:pattern,
  'getcommitFirstLine',
  'gitommitOverflow',
  join(['@Spell', 'gitcommitTrailingFullStop'], ',')
)

hi def link gitcommitTrailingFullStop Error
```
