### ISSUE TITLE
Allow using different comment character

### ISSUE THREAD

**Issue by hauleth** [tpope/vim-git#68]
Git allows to customise the comment character and I use `;` to not conflict with Markdown headers. It would be handy to be able to customise that in the syntax highlighting as well.

**Comment by davidosomething** [comment]
#59 #31 #27 
it's tough, and the solution without shelling is very difficult since git now supports includes in config

**Comment by hauleth** [comment]
For me it would be enough if I could set that manually without any shelling or other magic. Just plain `let g:gitcommit_comment = ';'` is more than enough.

**Comment by davidosomething** [comment]
is overriding this https://github.com/tpope/vim-git/blob/master/ftplugin/gitcommit.vim#L14
in an after/ftplugin enough? or did you want the colorscheme/syntax updates with it?

getting the syntax updates would require changing all the `syn` to `exec syn` or making two sets of it to dynamically change the syntax based on a variable. that also comes with some speed loss on initial syntax matching

**Comment by hauleth** [comment]
I would like to have syntax updated as well. These options I already set on my own. Of course I can do `after/syntax` as well, but I would prefer not to if that would be possible.

**Comment by tpope** [comment]
Try `let g:gitcommit_cleanup = 'scissors'` with `git config --global commit.cleanup scissors`. This fills largely the same need.

Custom comment characters could eventually happen. I've cleaned up the `#` repetition so at least the `:execute` problem is solved. But I want those changes to stabilize for a bit before I build anything on top of them.

One approach that might be worth considering is determining the comment character by looking at the contents of the buffer. In addition to sidestepping `system()`, this is probably the only way we can support `core.commentChar=auto`.
