### ISSUE TITLE
Feature request: different highlight for already pushed commits in interactive rebase

### ISSUE THREAD

**Issue by uusijani** [tpope/vim-git#71]
Having shot myself in the foot by rewriting already pushed history, it occurred to me that perhaps I could have the commits list in interactive rebase reflect the commits' push status in color. If lines of commits that I've already pushed to a remote were colored red (or any sufficiently differentiating color), I might actually notice when I'm about to screw up again.

To illustrate what I mean, here's a mockup I made. This is what it would look like if this was my commit history, and 8b0ce7b was the last commit I had already pushed to a remote:

![Kuvakaappaus 2020-08-19 15-52-35](https://user-images.githubusercontent.com/4244772/90640213-6217e300-e238-11ea-8fee-8333dd5c463f.png)

I have no previous experience in modifying syntax highlighting code, and I have no idea if what I'm suggesting is even possible with vim, so I figured I'd open this request first in case it's a silly idea, or conversely, if you deem this useful enough to implement yourself.

**Comment by tpope** [comment]
Not a bad idea, and almost certainly possible, but I would expect it to be a pretty hefty feature, and probably a bit much to include with Vim itself. I think the route to go here would be develop it as an external plugin and if it ends up being elegant and low maintenance, it could be considered for inclusion.
