### ISSUE TITLE
Gitignore filetype

### ISSUE THREAD

**Issue by maujim** [tpope/vim-git#73]
Are there any plans to provide support for `.gitignore` files?

**Comment by tpope** [comment]
The `conf` filetype already handles comments. So that basically just leaves highlighting `!` and maybe `*` which seems pretty low value to me? I don't see pursuing this.

**Comment by maujim** [comment]
Ok I didn't know about that, thanks

**Comment by tpope** [comment]
The `conf` type will apply automatically if there's a `#` comment in the first 5 lines of the file, which I've generally found to be good enough in practice.
