### ISSUE TITLE
Line in commit message that starts with a number confuses the auto indentation

### ISSUE THREAD

**Issue by ericonr** [tpope/vim-git#83]
Originally in https://github.com/neovim/neovim/issues/18396

Steps to reproduce:

- Set neovim as your git editor
- Run `git commit`
- Copy the commit message from https://github.com/lnls-dig/openMMC/pull/126/commits/fc56dedffff4781e4b0c06594f358aedb7cfe957
- Select the commit body and press `gq` to auto format it

The commit message in question:

```
fpga_spi: guarantee board_diagnostic_t alignment

fpga_spi.c reads from this struct by aliasing it to an uint32_t pointer
and using that to iterate through it. That means it should be aligned to
4 bytes, to so the reads don't generate faults, and that its size should
be a multiple of 4, otherwise we'd have to deal with defining incomplete
reads for the last element.
```

The commit body is changed to:

```
fpga_spi.c reads from this struct by aliasing it to an uint32_t pointer
and using that to iterate through it. That means it should be aligned to
4 bytes, to so the reads don't generate faults, and that its size should
  be a multiple of 4, otherwise we'd have to deal with defining
  incomplete reads for the last element.
```

Per https://github.com/neovim/neovim/issues/18396#issuecomment-1116741530 , this might not be possible to fix (or even considered a  bug):

> This is because the ftplugin for gitcommit sets formatoptions+=n and formatlistpat

But I'd like to bring it up to confirm.

**Comment by tpope** [comment]
Vim's default `'formatlistpat'` does this. You can change it in your vimrc to achieve the desired effect:

```vim
set formatlistpat=^\\s*\\d\\+[\\]:.)}]\\s\\+
```

I'm on the fence about whether `ftplugin/gitcommit.vim` should itself change this. The problem isn't "the default `'formatlistpat'` is bad for `gitcommit` files" but rather "the default `'formatlistpat'` is bad for _almost all_ files." I suppose we can try it on `master` for a bit and see if anyone complains.

**Comment by ericonr** [comment]
Thanks you!
