### ISSUE TITLE
 git word diff syntax highlighting breaks on empty line

### ISSUE THREAD

**Issue by step-** [tpope/vim-git#92]
The syntax file for filetype=git includes syntax patterns for git word diff mode (git --diff --word-diff). However, if the first line after the diffLine `@@` is empty the patterns fail to match and the whole diff block isn't highlighted anymore.

Example (set filetype=git):
```diff
@@ -124,7 +124,7 @@ typedef enum {
	BLOCK_NONE,
	BLOCK_STD,
	BLOCK_START
	BLOCK_[-DELETE-]{+ADD+},
	BLOCK_END,
} Mode;
```

Above `@@ -124...` is highlighted with diffLine, `typedef enum {` with diffSubname, `[-DELETE-]` with gitDiffRemoved and `{+ADD+}` with gitDiffAdded.
If I insert a line after `@@ -124...` the block of lines after `@@ -124...` stops being highlighted.

**Comment by tpope** [comment]
This is deliberate. Diffs never contain empty lines, so that's an easy way to tell if the diff is over.

(They can contain lines consisting of a single white space, which might *look* empty.)
